### ISSUE TITLE
Wrap library with #ifndef?

### ISSUE THREAD

**Issue by lawnmowerlatte** [adafruit/Adafruit_LED_Backpack#18]
Is there are reason the library is not wrapped in `#ifndef`/`#define`/`#endif` blocks? I'll admit that I'm a novice C coder, but I was having problems with using this library inside another object. I had to add #include to both my main sketch and the class itself but this resulted in redefinition issues until I added these lines at the top:

```
#ifndef Adafruit_LEDBackpack_h
#define Adafruit_LEDBackpack_h
```

and this at the bottom:

```
#endif
```

You can see the full issue on my question at [StackExchange](http://arduino.stackexchange.com/questions/8754/error-class-does-not-name-a-type-only-when-creating-object-inside-another-obj/8757#8757), including what I'm trying to accomplish.

Perhaps I'm going about this all wrong, but I'd be interested to see what your thoughts on this are. This is using Arduino IDE 1.0.6, so this may be a quirk of the IDE.

**Comment by frostyfrog** [comment]
I'll have to agree with you. Currently, the Adafruit libraries will only work when you include it once in your project. This is great if you are doing all your Adafruit coding in a single file, but it doesn't work well when you use a multi-file hierarchy.
