### ISSUE TITLE
Function "swap" has been changed in Adafruit-GFX-Library

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_LED_Backpack#28]
Ref. this commit: https://github.com/adafruit/Adafruit-GFX-Library/commit/944f3d9d9fa5255726929c4eeb499cde1daaedfa

See note there from mindcrime-ilab.

**Comment by PaintYourDragon** [comment]
This was an ugly "shouldn't have been exposed in the header file in the first place" macro. Sketches should implement their own swap-type function(s) for suitable data types as needed.
