### ISSUE TITLE
 Function "adagfxswap" has been changed and moved in Adafruit-GFX-Library 

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_LED_Backpack#29]
Ref. this commit: https://github.com/adafruit/Adafruit-GFX-Library/commit/f5ec45e42b7216ca3fa34eb08ec052071d672422

#define moved to .cpp file, so no longer accessible.

**Comment by PaintYourDragon** [comment]
This was an ugly "shouldn't have been exposed in the header file in the first place" macro. Sketches should implement their own swap-type function(s) for suitable data types as needed.
