### ISSUE TITLE
Wrong digit location for padding minutes in clock examples

### ISSUE THREAD

**Issue by haku15** [adafruit/Adafruit_LED_Backpack#36]
Just a minor issue in the examples "clock_sevenseg_ds1307" and "clock_sevenseg_gps".
The code for padding minutes:
```
 if (minutes < 10) {
      clockDisplay.writeDigitNum(2, 0);
}
```
should be
```
 if (minutes < 10) {
      clockDisplay.writeDigitNum(3, 0);
}
```
because 3 is the third digit from the left, at least for the Adafruit "4-digit 0.56" 7-segment".
Example with clockDisplay.writeDigitNum(2, 0) :  
_0:_3
Example with clockDisplay.writeDigitNum(3, 0) :  
_0:03

**Comment by caternuson** [comment]
Thanks. Hopefully fixed (finally) with #60.
