### ISSUE TITLE
Want to Scroll Array in 8x8 matrix

### ISSUE THREAD

**Issue by LedArts** [adafruit/Adafruit_LED_Backpack#38]
Hello Dear Master,
i want to scroll an Array in this code horizontaly and vertically 8x8 matrix plz help me

#include <Adafruit_NeoPixel.h>
#define PIN 6
#define MAX_LED 64
uint32_t LEDColour;
unsigned char x = 0;
unsigned char Colour[3];
unsigned char heart[10] = {12, 13, 17, 20, 26, 29, 33, 36, 44, 45};

Adafruit_NeoPixel strip = Adafruit_NeoPixel( MAX_LED, PIN, NEO_RGB + NEO_KHZ800 );
void setup() {
// put your setup code here, to run once:
strip.begin();
//
strip.show();
}

void loop() {

for (char number = 0; number < 64; number++) //
strip.setPixelColor(number, 0);
strip.show();//

// delay(1000);
for (char number = 0; number < 10; number++) //
strip.setPixelColor(heart[number], 255,0,0); // i want to scroll that heart array
strip.show();//
delay(1000);
}

**Comment by caternuson** [comment]
This is a different library. The NeoPixel library is here:
https://github.com/adafruit/Adafruit_NeoPixel
