### ISSUE TITLE
Conflict with feather SPI flash library

### ISSUE THREAD

**Issue by ChrisInSingapore** [adafruit/Adafruit_LED_Backpack#45]
Both this library and the other feather library SPIFlash define and use BYTE.  It would be good to use a different name in this library.  The issue is fully described here:
https://forums.adafruit.com/viewtopic.php?f=57&t=143261

**Comment by caternuson** [comment]
Conflict between here:
https://github.com/adafruit/Adafruit_LED_Backpack/blob/master/Adafruit_LEDBackpack.h#L135
and here:
https://github.com/adafruit/Adafruit_SPIFlash/blob/master/utility/diskio.h#L15

**Comment by caternuson** [comment]
Hopefully fixed with #63
