### ISSUE TITLE
Dependencies are too broad on PalatformIO

### ISSUE THREAD

**Issue by 101100** [adafruit/Adafruit_LED_Backpack#52]
The dependencies of the library are too broad.  I tried using the library in a PlatformIO project on a Huzzah32 and it would not compile due to the `WaveHC` dependency that the library does not really need.  Even if it did compile, it takes a really long time due to all of the unneeded dependencies.

Specifically here:

https://github.com/adafruit/Adafruit_LED_Backpack/blob/8ac14abaf77beab2c92b1729ab8404c917653ed2/library.properties#L9

this should only be:

```
depends=Adafruit GFX Library
```

**Comment by ladyada** [comment]
hihi i think this is fixed in the latest version of PlatformIO that @ivankravets just pushed here
https://github.com/platformio/platformio-core/issues/3607
