### ISSUE TITLE
Change ASCII "I" to make easier to read (Suggestion)

### ISSUE THREAD

**Issue by BKeyport** [adafruit/Adafruit_LED_Backpack#55]
- Arduino board:  N/A

- Arduino IDE version (found in Arduino -> About Arduino menu): N/A

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too):
  
Please change the binary in Adafruit_LEDBackpack.cpp as follows: 

Replace ``` 0b0001001000000000, // I ``` with  ``` 0b0001001000001001, // I ```

This produces a capital I with serif so that it's easier to tell it between I and 1. 
  
Anyone that stumbles across this could do it themselves, but I figure it might as well be in the default code.

**Comment by ladyada** [comment]
hi sounds good, please submit a PR!
