### ISSUE TITLE
blinkRate() description is incorrect

### ISSUE THREAD

**Issue by ricknun** [adafruit/Adafruit_LED_Backpack#69]
http://adafruit.github.io/Adafruit_LED_Backpack/html/class_adafruit___l_e_d_backpack.html
says the parameter for Public Member Function blinkRate() is "One of:
HT16K33_BLINK_DISPLAYON = steady on
HT16K33_BLINK_OFF = steady off
HT16K33_BLINK_2HZ = 2 Hz blink
HT16K33_BLINK_1HZ = 1 Hz blink
HT16K33_BLINK_HALFHZ = 0.5 Hz blink"

I think HT16K33_BLINK_DISPLAYON is not meant to be used as a parameter to blinkRate(), and that HT16K33_BLINK_OFF means "no blinking, steady on", the opposite of "steady off".

**Comment by caternuson** [comment]
Good catch. Seems correct. Only the `B1` and `B0` bits should be set:
![image](https://user-images.githubusercontent.com/8755041/158476775-61dd00bc-2052-464e-942d-83887b61505c.png)

The `HT16K33_BLINK_DISPLAYON` value is OR'd in manually:
https://github.com/adafruit/Adafruit_LED_Backpack/blob/508c0e6694d5197e598f81b5ca0337f58ddd1940/Adafruit_LEDBackpack.cpp#L272-L277

Want to PR a fix? The documentation is generated from the doc string comments in the library code. So just need to update this:
https://github.com/adafruit/Adafruit_LED_Backpack/blob/508c0e6694d5197e598f81b5ca0337f58ddd1940/Adafruit_LEDBackpack.h#L79-L87
I think just delete the one line that references `HT16K33_BLINK_DISPLAYON`.

**Comment by ricknun** [comment]
> I think just delete the one line that references HT16K33_BLINK_DISPLAYON.

That would leave "HT16K33_BLINK_OFF = steady off" that to me says "the display is steady off" and seems wrong. ""HT16K33_BLINK_OFF = no blinking" would be clearer.

**Comment by caternuson** [comment]
Yep, that'd be fine too.

**Comment by caternuson** [comment]
Closing. Fixed with #85.
