### ISSUE TITLE
1 segment consistently missing on each character with Adafruit 14-segment backpack

### ISSUE THREAD

**Issue by pomplesiegel** [adafruit/Adafruit_LED_Backpack#73]
Hello! In general this library is working very well for me. However, I have encountered one issue: 

For all of the characters on my Adafruit 14 segment backpack + diplay there is one segment missing. It is the right middle dash location. See image below: 

![IMG_0538](https://user-images.githubusercontent.com/1450352/209604463-88afe228-8e41-4cec-9056-ece02abd01e3.JPG)

I have found that this occurs whether I am using `writeDigitNum()` or `writeDigitAscii()`. Everything displays correctly except this one segment. 

Any thoughts? 
Thank you!

Library version: 1.3.2
Device: Teensy 4.1 
Platform: "arduino" via PlatformIO

**Comment by ladyada** [comment]
its probably hardware/soldering issue. for tech support please post to the forums

**Comment by pomplesiegel** [comment]
Hello, 

I’ll check again when I have the hardware in front of me but I believe the segment DOES illuminate if you write a 0xFF raw value to the unit. 

Also it occurs on all of my displays, and I double checked and repeated all soldering after I noticed the issue.

Would you mind checking if you see the same issue on your unit using the same software and hardware?

Thank you,
Michael

**Comment by pomplesiegel** [comment]
Hello @ladyada 

Indeed, if I write `writeDigitRaw(0,0xFF)` all of the segments successfully illuminate, as shown in the picture below. Therefore I believe this is a library issue, not a hardware problem. 

Would you mind testing to see if you can replicate the issue as well? 

Thank you! 

![IMG_0720](https://user-images.githubusercontent.com/1450352/210128565-9500124c-4fbe-496a-abd3-d3d3bcacf2df.JPG)

**Comment by ladyada** [comment]
@pomplesiegel can you post non-platformio (we dont use it) arduino example sketch we can use to replicate? our test code works fine so we're thinking its maybe an edge case?

**Comment by pomplesiegel** [comment]
@ladyada, thanks for the response! 

Just tried using Arduino IDE (Technically Teensyduino) with the latest version of this library library + dependencies via Arduino IDE's library interface, and it reproduces the issue. 

The issue occurs on my Teensy 4.1 + LED backpack hardware when I run the following simple code: 

````cpp
#include "Adafruit_LEDBackpack.h"

Adafruit_7segment display = Adafruit_7segment();

void setup() {
  display.begin(0x70);
}

void loop() {
  display.writeDigitNum(0, 4 ); //digit 0
  display.writeDigitNum(1, 5 ); //digit 1
  display.writeDigitNum(2, 8 ); //digit 2
  display.writeDisplay();
  delay(100);
}
````

See resulting picture of actual display output missing a segment: 

![IMG_0781](https://user-images.githubusercontent.com/1450352/210168838-07f6b340-16a3-46a2-8225-a7e8ba1aa80f.JPG)

**Comment by dhalbert** [comment]
Hi - You're using the 7-segment part of the library on a 14-segment display. Use the `Adafruit_AlphaNum4` class instead of the `Adafruit_7segment` class. See here: https://learn.adafruit.com/14-segment-alpha-numeric-led-featherwing/usage. In the Arduino library, there are also  `quadalphanum*` examples.

**Comment by pomplesiegel** [comment]
@dhalbert , indeed that was the issue! Just changed everything to the Adafruit_AlphaNum4 class, adding 48 to my numeric values in order to get the right ASCII character, and the display is now working perfectly.

I apologize for the silly error and false alarm. Thank you all for your help!
