### ISSUE TITLE
problem pre-install sequence in pull request automator

### ISSUE THREAD

**Issue by phd0** [adafruit/Adafruit_LED_Backpack#86]
In pull request  sequence, the pre-install sequence does not go correctly.
**ci/actions_install.sh**: line 40: {: ```command not found```

![image](https://github.com/adafruit/Adafruit_LED_Backpack/assets/1939211/4aaeff44-fc5a-46ce-b923-9decb372e56c)

this error did not appear in a previous sequence in November 2023. 
see https://github.com/adafruit/Adafruit_LED_Backpack/pull/78/checks

**Comment by caternuson** [comment]
An issue for this has already been opened in the repo containing the CI script:
https://github.com/adafruit/ci-arduino/issues/178

Note it's just a warning and should generally not affect having CI pass.

**Comment by tyeth** [comment]
Closing this as complete (CI should be fixed, please reopen if newly run actions experience a similar issue)
